### ISSUE TITLE
Package outdated

### ISSUE THREAD

**Issue by vanyasem** [Fab-IT-ApS/chocolatey-qtpass#1]
The package for Windows is outdated for more than a year.

https://chocolatey.org/packages/qtpass - QtPass v1.1.3
The latest upstream version is v1.2.1 as of now

**Comment by cmol** [comment]
Hi,

I just poked around to find the status of this.
We are in the process of transferring the maintenance to the creator @annejan, but the transfer is still pending. I'll look into it, but we won't be maintaining this going forward.

**Comment by annejan** [comment]
Let me know what I can do to help . .

**Comment by cmol** [comment]
@annejan, I've send you an email so we can get this transfer sorted out :)

**Comment by cmol** [comment]
@vanyasem, the ownership has been transferred to @annejan, so things should be a bit easier workflow wise now. Thanks for letting me know so we could fix this!
